# Generated by Django 2.0.13 on 2019-06-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_posts_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
