# Generated by Django 2.0.13 on 2019-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190625_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
